/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2018-04-18 07:03:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import com.ooad.web.model.Item;
import java.io.IOException;
import com.ooad.web.dao.ItemCategoryDao;
import com.ooad.web.model.ItemCategory;
import com.ooad.web.utils.TokenAuth;
import com.ooad.web.model.User;
import java.util.ArrayList;
import com.ooad.web.model.ItemSubCategory;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/jsp/header.jsp", Long.valueOf(1523943072000L));
    _jspx_dependants.put("/jsp/footer.jsp", Long.valueOf(1523943072000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.ooad.web.utils.TokenAuth");
    _jspx_imports_classes.add("com.ooad.web.model.ItemCategory");
    _jspx_imports_classes.add("com.ooad.web.dao.ItemCategoryDao");
    _jspx_imports_classes.add("com.ooad.web.model.ItemSubCategory");
    _jspx_imports_classes.add("com.ooad.web.model.User");
    _jspx_imports_classes.add("java.io.IOException");
    _jspx_imports_classes.add("com.ooad.web.model.Item");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("    <link rel=\"icon\" href=\"images/Amazon.ico\" type=\"image/x-icon\">\n");
      out.write("    <title>\n");
      out.write("        Amazon.com: Online Shopping for Electronics, Apparel, Computers, Books, DVDs &amp; more</title>\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/bootstrap.min.css\">\n");
      out.write("    <script src=\"js/jquery.min.js\"></script>\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/index.css\">\n");
      out.write("\n");
      out.write("    <script src=\"js/index.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
 Cookie[] cookies = request.getCookies();
   User user = null;
   if(cookies != null){
       for(Cookie cookie: cookies){
           if(cookie.getName().equals("authToken")){
                user = TokenAuth.getUserFromToken(cookie.getValue());
           }
       }
   }

      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/fontawesome-all.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"\">\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/bootstrap.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/bootstrap-dropdownhover.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/header.css\">\n");
      out.write("<script type=\"text/javascript\" src=\"../js/jquery.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"../js/bootstrap.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.cookie.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"http://maps.googleapis.com/maps/api/js?sensor=false\"></script>\n");
      out.write("<script src=\"../js/bootstrap-dropdownhover.js\"></script>\n");
      out.write("<script src=\"js/header.js\"></script>\n");
      out.write("<header class=\"container-fluid header\">\n");
      out.write("    <div class=\"row nav-belt \">\n");
      out.write("        <div class=\"logo col-lg-2 col-md-2\">\n");
      out.write("            <a href=\"/\" class=\"nav-logo-link\"><img src=\"#\" alt=\"\" style=\"text-color: white\">E-Store</a>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-lg-6 col-md-6\">\n");
      out.write("            <div class=\"row  search-box \">\n");
      out.write("                <form action=\"\" id=\"item-search\" style=\"height: inherit\">\n");
      out.write("                    <div class=\"col-lg-2 col-md-2 search-category\">\n");
      out.write("                        <select name=\"\" id=\"nav-search-select\">\n");
      out.write("                            <option value=\"all\">All Categories</option>\n");
      out.write("                            ");
 final ItemCategoryDao itemCategoryDao = new ItemCategoryDao();
                                ArrayList<ItemCategory> itemCategories = (ArrayList<ItemCategory>) itemCategoryDao.getAllCategories();
                                for (ItemCategory itemCategory : itemCategories) { 
      out.write("\n");
      out.write("                            <option value=\"");
      out.print( itemCategory.getName());
      out.write('"');
      out.write('>');
      out.print( itemCategory.getDisplayName());
      out.write("\n");
      out.write("                            </option>\n");
      out.write("                            ");
 }
      out.write("\n");
      out.write("                            <option>All Categories</option>\n");
      out.write("                        </select>\n");
      out.write("                    </div>\n");
      out.write("                    <input class=\"col-lg-9 col-md-9 search-input\" type=\"text\">\n");
      out.write("                    <div class=\"col-lg-1 col-md-1 search-icon\" id=\"search-icon\">\n");
      out.write("                        <i class=\"fa fa-search fa-1g pull-right icn\" aria-hidden=\"true\"></i>\n");
      out.write("                    </div>\n");
      out.write("                </form>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-lg-4 col-md-4\">\n");
      out.write("            ");
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"row nav-main\">\n");
      out.write("        <div class=\"col-lg-3 col-md-3\">\n");
      out.write("            <div class=\"row nav-left\">\n");
      out.write("                <div class=\"col-md-6 nav-border-round\">\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"col-md-2 \" id=\"map-location-picker\">\n");
      out.write("                            <img src=\"../images/location.png\" alt=\"\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-md-10\" id=\"nav-deliver-div\">\n");
      out.write("                            <a href=\"#\" id=\"nav-deliver\">\n");
      out.write("                                <span style=\"font-size: 12px;font-weight: 400; \">Deliver to\n");
      out.write("                                    ");
      out.print( (user==null)? "" : user.getUserName() );
      out.write(" </span>\n");
      out.write("                                <br><p id=\"loc\"></p>\n");
      out.write("                            </a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-6\">\n");
      out.write("                    <div class=\"dropdown nav-border-round\">\n");
      out.write("                        <a class=\"dropdown-toggle\" type=\"button\" id=\"nav-shopby\" data-toggle=\"dropdown\"\n");
      out.write("                           data-hover=\"dropdown\">\n");
      out.write("                            <span style=\"font-size: 12px; font-weight: 400\">shop by</span>\n");
      out.write("                            <br>Category <i class=\"fa fa-caret-down\" aria-hidden=\"true\"></i>\n");
      out.write("                        </a>\n");
      out.write("                        <ul class=\"dropdown-menu\">\n");
      out.write("                            ");
for (ItemCategory itemCategory : itemCategories) { 
      out.write("\n");
      out.write("                            <li class=\"dropdown\">\n");
      out.write("                                <a href=\"#\">");
      out.print(itemCategory.getDisplayName());
      out.write("</a>\n");
      out.write("                                ");
 if(itemCategory.getDisplayName().equals("Others")) continue;
      out.write("\n");
      out.write("                                <ul class=\"dropdown-menu\">\n");
      out.write("                                    ");
 ArrayList<ItemSubCategory> itemsubCategories = (ArrayList<ItemSubCategory>) itemCategoryDao.getAllsubCategories(itemCategory.getId());
                                        for (ItemSubCategory itemsubCategory : itemsubCategories) { 
      out.write("\n");
      out.write("                                        <li><a href=\"/items?category=");
      out.print(itemCategory.getName());
      out.write("&subcategory=");
      out.print(itemsubCategory.getDisplayName());
      out.write('"');
      out.write('>');
      out.print(itemsubCategory.getDisplayName());
      out.write("</a></li>\n");
      out.write("                                    ");
}
      out.write("\n");
      out.write("                                </ul>\n");
      out.write("                            </li>\n");
      out.write("                            ");
}
      out.write("\n");
      out.write("                        </ul>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-lg-5 col-md-6\">\n");
      out.write("            <div class=\"row nav-fill\">\n");
      out.write("                <br>\n");
      out.write("                <a href=\"#\">\n");
      out.write("                    ");
      out.print( (user==null)? "your":user.getUserName());
      out.write("\n");
      out.write("                    Accout</a> &nbsp;&nbsp;&nbsp;\n");
      out.write("                <a href=\"/amazonpay\">Wallet</a>&nbsp;&nbsp;&nbsp;\n");
      out.write("                <a href=\"/sellerlogin\">Sell</a>&nbsp;&nbsp;&nbsp;\n");
      out.write("                ");
 if(user!=null && user.getEmailId().equals("admin@admin.com")) { 
      out.write("\n");
      out.write("                    <a href=\"/admin\">admin</a> &nbsp;&nbsp;\n");
      out.write("                ");
}
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-lg-4 col-md-3\">\n");
      out.write("            <div class=\"row nav-left\">\n");
      out.write("                <div class=\"col-md-4 nav-border-round\" id=\"nav-account\">\n");
      out.write("                    ");
 if(user == null) {
      out.write("\n");
      out.write("                        <a href=\"/login\">\n");
      out.write("                            <span class=\"nav-line-1\">Hello, Sign in </span><br>\n");
      out.write("                            <span class=\"nav-line-2\">Your Orders</span>\n");
      out.write("                            <i class=\"fa fa-caret-down\" aria-hidden=\"true\"></i>\n");
      out.write("                        </a>\n");
      out.write("                    ");
 } else { 
      out.write("\n");
      out.write("                    <div class=\"dropdown nav-border-round\">\n");
      out.write("                        <a href=\"#\" class=\"dropdown-toggle\" id = \"nav-signIn\" data-toggle=\"dropdown\" data-hover=\"dropdown\">\n");
      out.write("                            <span class=\"nav-line-1\">Hello ");
      out.print( user.getUserName());
      out.write(" </span><br>\n");
      out.write("                            <span class=\"nav-line-2\">Your Orders</span>\n");
      out.write("                            <i class=\"fa fa-caret-down\" aria-hidden=\"true\"></i>\n");
      out.write("                        </a>\n");
      out.write("                        <ul class=\"dropdown-menu\">\n");
      out.write("                            <li><a href=\"#\" id=\"nav-logout\">Logout</a></li>\n");
      out.write("                            <li><a href=\"#\">Your account</a></li>\n");
      out.write("                            <li><a href=\"/list\">Your List</a></li>\n");
      out.write("                            <li><a href=\"/myorders\">Your Orders</a></li>\n");
      out.write("                        </ul>\n");
      out.write("                    </div>\n");
      out.write("                    ");
}
      out.write("\n");
      out.write("                </div>\n");
      out.write("                ");
      out.write("\n");
      out.write("                    ");
      out.write("\n");
      out.write("                        ");
      out.write("\n");
      out.write("                        ");
      out.write("\n");
      out.write("                        ");
      out.write("\n");
      out.write("                    ");
      out.write("\n");
      out.write("                ");
      out.write("\n");
      out.write("                <div class=\"col-md-3 nav-border-round\" id=\"nav-yourlist\">\n");
      out.write("                    <a href=\"/list\">\n");
      out.write("                        <span class=\"nav-line-1\">Your </span><br>\n");
      out.write("                        <span class=\"nav-line-2\">Lists </span> <i class=\"fa fa-caret-down\" aria-hidden=\"true\"></i>\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("                <a href=\"/cart\">\n");
      out.write("                    <div class=\"col-md-3 cart\">\n");
      out.write("                        <span id=\"cart-contents\">");
      out.print((user==null)? 0:user.getCart().size());
      out.write("</span>\n");
      out.write("                    </div>\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</header>");
      out.write('\n');
 ArrayList<Item> items = Item.getLastFive();
      out.write("\n");
      out.write("<section id=\"promo\">\n");
      out.write("    <div class=\"container-fluid\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <div class=\"col-lg-12\">\n");
      out.write("                <div id=\"promo-carousel\" class=\"carousel slide\" data-ride=\"carousel\">\n");
      out.write("\n");
      out.write("                    <!-- Indicators -->\n");
      out.write("                    <ol class=\"carousel-indicators\">\n");
      out.write("                        <li data-target=\"#promo-carousel\" data-slide-to=\"0\" class=\"active\"></li>\n");
      out.write("                        <li data-target=\"#promo-carousel\" data-slide-to=\"1\"></li>\n");
      out.write("                        <li data-target=\"#promo-carousel\" data-slide-to=\"2\"></li>\n");
      out.write("                        <li data-target=\"#promo-carousel\" data-slide-to=\"3\"></li>\n");
      out.write("                        <li data-target=\"#promo-carousel\" data-slide-to=\"4\"></li>\n");
      out.write("                        <li data-target=\"#promo-carousel\" data-slide-to=\"5\"></li>\n");
      out.write("                    </ol>\n");
      out.write("                    <!-- Wrapper for slides -->\n");
      out.write("                    <div class=\"carousel-inner\">\n");
      out.write("                        <div class=\"item active\">\n");
      out.write("                            <img src=\"../images/carousel/Echo alexa.jpg\" alt=\"Echo alexa\" style=\"width:120%;\">\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"item\">\n");
      out.write("                            <img src=\"../images/carousel/Index.png\" alt=\"Index\" style=\"width:100%;\">\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"item\">\n");
      out.write("                            <img src=\"../images/carousel/Redmi 4.png\" alt=\"Redmi 4 \" style=\"width:100%;\">\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"item\">\n");
      out.write("                            <img src=\"../images/carousel/Shave it of.png\" alt=\"Shave it of\" style=\"width:100%;\">\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"item\">\n");
      out.write("                            <img src=\"../images/carousel/Gaming .png\" alt=\"Gaming \" style=\"width:100%;\">\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"item\">\n");
      out.write("                            <img src=\"../images/carousel/bottle .jpg\" alt=\"bottles and flasks \" style=\"width:100%;\">\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <!-- Controls -->\n");
      out.write("                        <a class=\"left carousel-control\" href=\"#promo-carousel\" role=\"button\" data-slide=\"prev\">\n");
      out.write("                            <span class=\"glyphicon glyphicon-chevron-left\"></span>\n");
      out.write("                            <span class=\"sr-only\">Previous</span>\n");
      out.write("                        </a>\n");
      out.write("                        <a class=\"right carousel-control\" href=\"#promo-carousel\" role=\"button\" data-slide=\"next\">\n");
      out.write("                            <span class=\"glyphicon glyphicon-chevron-right\"></span>\n");
      out.write("                            <span class=\"sr-only\">Next</span>\n");
      out.write("                        </a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("<div class=\"container-fluid\">\n");
      out.write("    <div class='row'>\n");
      out.write("        <div class='col-md-8'>\n");
      out.write("            <div class=\"carousel slide media-carousel\" id=\"media\">\n");
      out.write("                <div class=\"carousel-inner\">\n");
      out.write("                    ");

                        int i = 0,j=0;
                        while(i < items.size()){
                            if(i%3==0){ 
      out.write("\n");
      out.write("                                <div class=\"item  ");
      out.print( (i==0) ? "active":"");
      out.write("\">\n");
      out.write("                                    <div class=\"row\">\n");
      out.write("                                    ");

                                        while(i<items.size() && j <3) {
                                            final Item item = items.get(i); 
      out.write("\n");
      out.write("                                            <div class=\"col-md-4\">\n");
      out.write("                                                <div class='card'>\n");
      out.write("                                                    <img class='card-img-top' src='");
      out.print( item.getUrl() );
      out.write("' alt='card image cap' style=\"height: 160px; width: 160px\">\n");
      out.write("                                                    <div class=\"card-body\">\n");
      out.write("                                                        <h5 class=\"card-title\">");
      out.print(item.getName());
      out.write("</h5>\n");
      out.write("                                                        <p class=\"card-text\">Price ");
      out.print(item.getPrice());
      out.write("</p>\n");
      out.write("                                                        <a href=\"/item?id=");
      out.print(item.getId());
      out.write("\">Buy</a>\n");
      out.write("                                                    </div>\n");
      out.write("                                                </div>\n");
      out.write("                                            </div>\n");
      out.write("                                            ");
i++;
                                            j++;
                                        }
                                        j=0;
                                    
      out.write("\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            ");
}
                        }
      out.write("\n");
      out.write("                    <a data-slide=\"prev\" href=\"#media\" class=\"left carousel-control\"> < </a>\n");
      out.write("                    <a data-slide=\"next\" href=\"#media\" class=\"right carousel-control\"> > </a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"row\">\n");
      out.write("        <a href=\"/report\">Report</a>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/footer.css\">\n");
      out.write("<div class='navLeftFooter nav-sprite-v1' id='navFooter'>\n");
      out.write("    ");
      out.write("\n");
      out.write("        ");
      out.write("\n");
      out.write("            ");
      out.write("\n");
      out.write("    ");
      out.write("\n");
      out.write("    <table class=\"navFooterVerticalColumn\" cellspacing=\"0\" align=\"center\" role=\"presentation\">\n");
      out.write("        <tr>\n");
      out.write("            <td class=\"navFooterLinkCol\">\n");
      out.write("                <div class=\"navFooterColHead\">Get to Know Us</div>\n");
      out.write("                <ul>\n");
      out.write("                    <li class='nav_first'><a href=\"#\" class='nav_a'>About Us</a></li>\n");
      out.write("                    <li><a href=\"#\" class='nav_a'>Careers</a></li>\n");
      out.write("                    <li><a href=\"#\" class='nav_a'>Press Releases</a></li>\n");
      out.write("                    <li><a href=\"#\" class='nav_a'>Amazon Cares</a></li>\n");
      out.write("                    <li class='nav_last'><a href=\"#\" class='nav_a'>Gift a Smile</a></li>\n");
      out.write("                </ul>\n");
      out.write("            </td>\n");
      out.write("            <td class=\"navFooterColSpacerInner\"></td>\n");
      out.write("            <td class=\"navFooterLinkCol\">\n");
      out.write("                <div class=\"navFooterColHead\">Connect with Us</div>\n");
      out.write("                <ul>\n");
      out.write("                    <li class='nav_first'><a href=\"#\" class='nav_a'>Facebook</a></li>\n");
      out.write("                    <li><a href=\"#\" class='nav_a'>Twitter</a></li>\n");
      out.write("                    <li class='nav_last'><a href=\"#\" class='nav_a'>Instagram</a></li>\n");
      out.write("                </ul>\n");
      out.write("            </td>\n");
      out.write("            <td class=\"navFooterColSpacerInner\"></td>\n");
      out.write("            <td class=\"navFooterLinkCol\">\n");
      out.write("                <div class=\"navFooterColHead\">Make Money with Us</div>\n");
      out.write("                <ul>\n");
      out.write("                    <li class='nav_first'><a href=\"#\" class='nav_a'>Sell on Amazon</a></li>\n");
      out.write("                    <li><a href=\"#\" class='nav_a'>Become an Affiliate</a></li>\n");
      out.write("                    <li><a href=\"#\" class='nav_a'>Fulfilment by Amazon</a></li>\n");
      out.write("                    <li><a href=\"#\" class='nav_a'>Advertise Your Products</a></li>\n");
      out.write("                    <li class='nav_last'><a href=\"#\" class='nav_a'>Amazon Pay on Merchants</a></li>\n");
      out.write("                </ul>\n");
      out.write("            </td>\n");
      out.write("            <td class=\"navFooterColSpacerInner\"></td>\n");
      out.write("            <td class=\"navFooterLinkCol\">\n");
      out.write("                <div class=\"navFooterColHead\">Let Us Help You</div>\n");
      out.write("                <ul>\n");
      out.write("                    <li class='nav_first'><a href=\"#\" class='nav_a'>Your Account</a></li>\n");
      out.write("                    <li><a href=\"#\" class='nav_a'>Returns Centre</a></li>\n");
      out.write("                    <li><a href=\"#\" class='nav_a'>100% Purchase Protection</a></li>\n");
      out.write("                    <li><a href=\"#\" class='nav_a'>Amazon Assistant</a></li>\n");
      out.write("                    <li class='nav_last'><a href=\"#\" class='nav_a'>Help</a></li>\n");
      out.write("                </ul>\n");
      out.write("            </td>\n");
      out.write("        </tr>\n");
      out.write("    </table>\n");
      out.write("    <div class=\"nav-footer-line\"></div>\n");
      out.write("    <div class=\"navFooterLine navFooterLogoLine\">\n");
      out.write("        <a href=\"#\">\n");
      out.write("            <img src=\"# alt=\"Amazon\">\n");
      out.write("        </a>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"navFooterLine navFooterLinkLine navFooterPadItemLine \">\n");
      out.write("        <ul>\n");
      out.write("            <li class='nav_first'><a href=\"#\" class='nav_a'>Australia</a></li>\n");
      out.write("            <li><a href=\"#\" class='nav_a'>Brazil</a></li>\n");
      out.write("            <li><a href=\"#\" class='nav_a'>Canada</a></li>\n");
      out.write("            <li><a href=\"#\" class='nav_a'>China</a></li>\n");
      out.write("            <li><a href=\"#\" class='nav_a'>France</a></li>\n");
      out.write("            <li><a href=\"#\" class='nav_a'>Germany</a></li>\n");
      out.write("            <li><a href=\"#\" class='nav_a'>Italy</a></li>\n");
      out.write("            <li><a href=\"#\" class='nav_a'>Japan</a></li>\n");
      out.write("            <li><a href=\"#\" class='nav_a'>Mexico</a></li>\n");
      out.write("            <li><a href=\"#\" class='nav_a'>Netherlands</a></li>\n");
      out.write("            <li><a href=\"#\" class='nav_a'>Spain</a></li>\n");
      out.write("            <li><a href=\"#\" class='nav_a'>United Kingdom</a></li>\n");
      out.write("            <li class='nav_last'><a href=\"#\" class='nav_a'>United States</a></li>\n");
      out.write("        </ul>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"navFooterLine navFooterLinkLine navFooterDescLine\">\n");
      out.write("        <table class=\"navFooterMoreOnAmazon\" cellspacing=\"0\">\n");
      out.write("            <tr>\n");
      out.write("                <td class=\"navFooterDescItem\"><a href=\"#\" class=\"nav_a\">AbeBooks<br/> <span class=\"navFooterDescText\">Books, art<br/> & collectibles</span></a>\n");
      out.write("                </td>\n");
      out.write("                <td class=\"navFooterDescSpacer\" style=\"width: 4%\"></td>\n");
      out.write("                <td class=\"navFooterDescItem\"><a href=\"#\" class='nav_a'>Amazon Web Services<br/> <span\n");
      out.write("                        class=\"navFooterDescText\">Scalable Cloud<br/> Computing Services</span></a></td>\n");
      out.write("                <td class=\"navFooterDescSpacer\" style=\"width: 4%\"></td>\n");
      out.write("                <td class=\"navFooterDescItem\"><a href=\"#\" class='nav_a'>Audible<br/> <span class=\"navFooterDescText\">Download<br/> Audio Books</span></a>\n");
      out.write("                </td>\n");
      out.write("                <td class=\"navFooterDescSpacer\" style=\"width: 4%\"></td>\n");
      out.write("                <td class=\"navFooterDescItem\"><a href=\"#\" class='nav_a'>DPReview<br/> <span class=\"navFooterDescText\">Digital<br/> Photography</span></a>\n");
      out.write("                </td>\n");
      out.write("                <td class=\"navFooterDescSpacer\" style=\"width: 4%\"></td>\n");
      out.write("                <td class=\"navFooterDescItem\"><a href=\"#\" class='nav_a'>IMDb<br/> <span class=\"navFooterDescText\">Movies, TV<br/> & Celebrities</span></a>\n");
      out.write("                </td>\n");
      out.write("                <td class=\"navFooterDescSpacer\" style=\"width: 4%\"></td>\n");
      out.write("                <td class=\"navFooterDescItem\"><a href=\"#\" class='nav_a'>Junglee.com<br/> <span\n");
      out.write("                        class=\"navFooterDescText\">Shop Online<br/> in India</span></a></td>\n");
      out.write("            </tr>\n");
      out.write("            <tr>\n");
      out.write("                <td>&nbsp;</td>\n");
      out.write("            </tr>\n");
      out.write("            <tr>\n");
      out.write("                <td class=\"navFooterDescItem\"><a href=\"#\" class='nav_a'>Look.com<br/> <span class=\"navFooterDescText\">Kids' Clothing<br/> & Shoes</span></a>\n");
      out.write("                </td>\n");
      out.write("                <td class=\"navFooterDescSpacer\" style=\"width: 4%\"></td>\n");
      out.write("                <td class=\"navFooterDescItem\"><a href=\"#\" class='nav_a'>Shopbop<br/> <span class=\"navFooterDescText\">Designer<br/> Fashion Brands</span></a>\n");
      out.write("                </td>\n");
      out.write("                <td class=\"navFooterDescSpacer\" style=\"width: 4%\"></td>\n");
      out.write("                <td class=\"navFooterDescItem\"><a href=\"#\" class='nav_a'>\n");
      out.write("                    Amazon Business<br/> <span class=\"navFooterDescText\">Everything For<br/> Your Business</span></a>\n");
      out.write("                </td>\n");
      out.write("                <td class=\"navFooterDescSpacer\" style=\"width: 4%\"></td>\n");
      out.write("                <td class=\"navFooterDescItem\"><a href=\"#\" class='nav_a'>Souq.com<br/> <span class=\"navFooterDescText\">Shop Online in the<br/> Middle East</span></a>\n");
      out.write("                </td>\n");
      out.write("                <td class=\"navFooterDescSpacer\" style=\"width: 4%\"></td>\n");
      out.write("                <td class=\"navFooterDescItem\"><a href=\"#\" class='nav_a'>Amazon Now<br/> <span class=\"navFooterDescText\"> 2-Hour Delivery<br/> on Everyday Items</span></a>\n");
      out.write("                </td>\n");
      out.write("                <td class=\"navFooterDescSpacer\" style=\"width: 4%\"></td>\n");
      out.write("                <td class=\"navFooterDescItem\">&nbsp;</td>\n");
      out.write("            </tr>\n");
      out.write("        </table>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"navFooterLine navFooterLinkLine navFooterPadItemLine navFooterCopyright\">\n");
      out.write("        <ul>\n");
      out.write("            <li class='nav_first'><a href=\"#\" class='nav_a'>Conditions of Use & Sale</a></li>\n");
      out.write("            <li><a href=\"#\" class='nav_a'>Privacy Notice</a></li>\n");
      out.write("            <li class='nav_last'><a href=\"#\" class='nav_a'>Interest-Based Ads</a></li>\n");
      out.write("        </ul>\n");
      out.write("        <span>Â© 1996-2018, Amazon.com, Inc. or its affiliates</span>\n");
      out.write("        <ul></ul>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
