/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2018-04-18 07:04:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html class=\"a-no-js\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <title dir=\"ltr\">Amazon Sign IN</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/bootstrap.min.css\">\n");
      out.write("\n");
      out.write("    <!-- <link rel=\"stylesheet\" href=\"https://images-na.ssl-images-amazon.com/images/I/61gbb09bfIL._RC|11Fd9tJOdtL.css,21ULbzscqzL.css,31Q3id-QR0L.css,31QszevPBSL.css_.css#AUIClients/AmazonUI.min\" /> -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/amazon1.css\"/>\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/amazon2.css\"/>\n");
      out.write("    <script src=\"../js/jquery.min.js\"></script>\n");
      out.write("    <script src=\"../js/jquery.cookie.js\"></script>\n");
      out.write("    <script src=\"../js/login.js\"></script>\n");
      out.write("    <!-- <link rel=\"stylesheet\" href=\"https://images-na.ssl-images-amazon.com/images/G/01/AUIClients/CVFAssets-e91ba5c6e67c58c7f9c4c413fa67697feade389e._V2_.css#AUIClients/CVFAssets.secure.min\" /> -->\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div id=\"alerts\"></div>\n");
      out.write("<div id=\"a-page\">\n");
      out.write("    <div class=\"a-section a-padding-medium auth-workflow\">\n");
      out.write("        <div class=\"a-section a-spacing-none auth-navbar\">\n");
      out.write("            ");
      out.write("\n");
      out.write("                ");
      out.write("\n");
      out.write("                    ");
      out.write("\n");
      out.write("                    ");
      out.write("\n");
      out.write("                ");
      out.write("\n");
      out.write("            ");
      out.write("\n");
      out.write("        </div>\n");
      out.write("        <div class=\"a-section a-spacing-base auth-pagelet-container\">\n");
      out.write("            <div id=\"auth-cookie-warning-message\" class=\"a-box a-alert a-alert-warning\">\n");
      out.write("                <div class=\"a-box-inner a-alert-container\">\n");
      out.write("                    <h4 class=\"a-alert-heading\">Please Enable Cookies to Continue</h4>\n");
      out.write("                    <i class=\"a-icon a-icon-alert\"></i>\n");
      out.write("                    <div class=\"a-alert-content\">\n");
      out.write("                        <p>\n");
      out.write("                            <a class=\"a-link-normal\" href=\"/gp/help/customer/display.html/ref=ap_cookie_error_help?\">\n");
      out.write("                            </a>\n");
      out.write("                        </p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"a-section auth-pagelet-container\">\n");
      out.write("\n");
      out.write("            <div class=\"a-section a-spacing-base\">\n");
      out.write("                <div class=\"a-section\">\n");
      out.write("                    <form name=\"signIn\" id = \"signIn\" novalidate action='#'>\n");
      out.write("                        <div class=\"a-section\">\n");
      out.write("                            <div class=\"a-box\">\n");
      out.write("                                <div class=\"a-box-inner a-padding-extra-large\">\n");
      out.write("                                    <h1 class=\"a-spacing-small\">\n");
      out.write("                                        Login\n");
      out.write("                                    </h1>\n");
      out.write("                                    <!-- optional subheading element -->\n");
      out.write("                                    <div class=\"a-row a-spacing-base\">\n");
      out.write("                                        <label for=\"ap_email\" class=\"a-form-label\">\n");
      out.write("                                            Email\n");
      out.write("                                        </label>\n");
      out.write("                                        <input type=\"email\" maxlength=\"128\" id=\"ap_email\" name=\"email\" tabindex=\"1\"\n");
      out.write("                                               class=\"a-input-text a-span12 auth-autofocus auth-required-field\">\n");
      out.write("                                        <br>\n");
      out.write("                                        <span class=\"error text-danger\" id=\"emailError\"></span>\n");
      out.write("                                        <span class=\"error text-danger\" id=\"verificationError\"></span>\n");
      out.write("\n");
      out.write("                                        <br>\n");
      out.write("                                        ");
      out.write("\n");
      out.write("                                        <label for=\"ap_password\" class=\"a-form-label\">\n");
      out.write("                                            Password\n");
      out.write("                                            <span class=\"right\"><a href=\"#\">Forgot your password?</a></span>\n");
      out.write("                                        </label>\n");
      out.write("\n");
      out.write("                                        <input type=\"password\" maxlength=\"128\" id=\"ap_password\" name=\"psword\"\n");
      out.write("                                               tabindex=\"1\"\n");
      out.write("                                               class=\"a-input-text a-span12 auth-autofocus auth-required-field\">\n");
      out.write("                                        <span class=\"error text-danger\" id=\"passwordError\"></span>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"a-section\">\n");
      out.write("                                    <span id=\"continue\" class=\"a-button a-button-span12 a-button-primary\">\n");
      out.write("                                        <span\n");
      out.write("                                            class=\"a-button-inner\">\n");
      out.write("                                        <input id=\"continue\" tabindex=\"5\"\n");
      out.write("                                                                          class=\"a-button-input\" type=\"submit\"\n");
      out.write("                                                                          aria-labelledby=\"continue-announce\">\n");
      out.write("                                        <span\n");
      out.write("                                            id=\"continue-announce\" name=\"btn-login\" class=\"a-button-text\" aria-hidden=\"true\">\n");
      out.write("                                    continue\n");
      out.write("                                    </span>\n");
      out.write("                                        </span>\n");
      out.write("                                    </span>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"a-section\">\n");
      out.write("                                        <div aria-live=\"polite\"\n");
      out.write("                                             class=\"a-row a-expander-container a-expander-inline-container\">\n");
      out.write("\n");
      out.write("                                            <div aria-expanded=\"false\"\n");
      out.write("                                                 class=\"a-expander-content a-expander-inline-content a-expander-inner\"\n");
      out.write("                                                 style=\"display:none\">\n");
      out.write("                                                <a id=\"auth-fpp-link-bottom\" class=\"a-link-normal\"\n");
      out.write("                                                   href=\"https://www.amazon.in/ap/forgotpassword?openid.pape.max_auth_age=0&openid.return_to=https%3A%2F%2Fwww.amazon.in%2Fgp%2Fyourstore%2Fhome%3Fie%3DUTF8%26action%3Dsign-out%26path%3D%252Fgp%252Fyourstore%252Fhome%26ref_%3Dnav_youraccount_nav_youraccount_signout%26signIn%3D1%26useRedirectOnSuccess%3D1&prevRID=FBET0ZQEF9FTK4P81YVP&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=inflex&openid.mode=checkid_setup&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&prepopulatedLoginId=&failedSignInCount=0&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&pageId=inflex&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0\">\n");
      out.write("                                                    Forgot Password\n");
      out.write("                                                </a>\n");
      out.write("                                            </div>\n");
      out.write("                                            <div aria-expanded=\"false\"\n");
      out.write("                                                 class=\"a-expander-content a-expander-inline-content a-expander-inner\"\n");
      out.write("                                                 style=\"display:none\">\n");
      out.write("                                                <a id=\"ap-other-signin-issues-link\" class=\"a-link-normal\"\n");
      out.write("                                                   href=\"/gp/help/customer/account-issues/ref=ap_login_with_otp_claim_collection?ie=UTF8\">\n");
      out.write("                                                    Other issues with sign in\n");
      out.write("                                                </a>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"a-divider a-divider-break\">\n");
      out.write("                    <h5>New Account?</h5>\n");
      out.write("                </div>\n");
      out.write("                <span id=\"auth-create-account-link\" class=\"a-button a-button-span12\"><span class=\"a-button-inner\"><a\n");
      out.write("                        id=\"createAccountSubmit\" tabindex=\"6\" href=\"/register\" class=\"a-button-text\" role=\"button\">\n");
      out.write("                  Create your New account\n");
      out.write("                  </a></span></span>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div id=\"right-2\">\n");
      out.write("        </div>\n");
      out.write("        <div class=\"a-section a-spacing-top-extra-large auth-footer\">\n");
      out.write("            <div class=\"a-divider a-divider-section\">\n");
      out.write("                <div class=\"a-divider-inner\"></div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"a-section a-spacing-small a-text-center a-size-mini\">\n");
      out.write("                <span class=\"auth-footer-seperator\"></span>\n");
      out.write("                <a class=\"a-link-normal\" target=\"_blank\" rel=\"noopener noreferrer\"\n");
      out.write("                   href=\"#\">\n");
      out.write("                    Conditions of Use\n");
      out.write("                </a>\n");
      out.write("                <span class=\"auth-footer-seperator\"></span>\n");
      out.write("                <a class=\"a-link-normal\" target=\"_blank\" rel=\"noopener noreferrer\"\n");
      out.write("                   href=\"#\">\n");
      out.write("                    Privacy Notice\n");
      out.write("                </a>\n");
      out.write("                <span class=\"auth-footer-seperator\"></span>\n");
      out.write("                <a class=\"a-link-normal\" target=\"_blank\" rel=\"noopener noreferrer\" href=\"#\">\n");
      out.write("                    Help\n");
      out.write("                </a>\n");
      out.write("                <span class=\"auth-footer-seperator\"></span>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"a-section a-spacing-none a-text-center\">\n");
      out.write("                  <span class=\"a-size-mini a-color-secondary\">\n");
      out.write("                  © 1996-2018, E-Store, Inc. or its affiliates\n");
      out.write("                  </span>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <div id=\"auth-external-javascript\" class=\"auth-external-javascript\" data-external-javascripts=\"\">\n");
      out.write("    </div>\n");
      out.write("    <!-- cache slot rendered -->\n");
      out.write("</div>\n");
      out.write("<div id='be' style=\"display:none;visibility:hidden;\">\n");
      out.write("    <form name='ue_backdetect' action=\"get\"><input type=\"hidden\" name='ue_back' value='1'/></form>\n");
      out.write("</div>\n");
      out.write("<noscript>\n");
      out.write("    <img height=\"1\" width=\"1\" style='display:none;visibility:hidden;'\n");
      out.write("         src='//fls-eu.amazon.com/1/batch/1/OP/A21TJRUUN4KGV:262-6062281-6227166:FBET0ZQEF9FTK4P81YVP$uedata=s:%2Fap%2Fuedata%3Fnoscript%26id%3DFBET0ZQEF9FTK4P81YVP:0'\n");
      out.write("         alt=\"\"/>\n");
      out.write("</noscript>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
